import { CityData, SpaceData } from "../../engine/state/space";
import { black, city, grid, PLAIN, town, UNPASSABLE, white } from "../factory";
import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { SpaceType } from "../../engine/state/location_type";
import { startFrom } from "../tile_factory";
import { BOTTOM_LEFT, TOP, TOP_LEFT } from "../../engine/state/tile";

export const CHICAGO_SAME_CITY = 1;

const CHICAGO_SIDE: CityData = {
  type: SpaceType.CITY,
  sameCity: CHICAGO_SAME_CITY,
  color: [RED],
  name: "",
  goods: [],
  onRoll: [],
  startingNumCubes: 0,
};
const CHICAGO_CENTER: CityData = {
  type: SpaceType.CITY,
  sameCity: CHICAGO_SAME_CITY,
  color: [RED],
  name: "To Chicago",
  goods: [],
  onRoll: [black(1), black(2)],
  startingNumCubes: 2,
};

export const map = grid<SpaceData>([
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    town("Cedar Lake"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Crown Point", YELLOW, white(4), 2),
    PLAIN,
    town("Winfield"),
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    city("Saint John", YELLOW, white(2), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Valparaiso", PURPLE, white(6), 3),
    {
      type: SpaceType.UNPASSABLE,
      tile: {
        ...startFrom(TOP).curveLeft(),
        claimableCost: [10],
      },
    },
  ],
  [
    UNPASSABLE,
    town("Dyer"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Merrillville", RED, white(3), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    {
      type: SpaceType.UNPASSABLE,
      tile: {
        ...startFrom(TOP_LEFT).straightAcross(),
      },
    },
  ],
  [
    PLAIN,
    PLAIN,
    city("Schererville", PURPLE, white(1), 3),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    UNPASSABLE,
    town("La Porte"),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Griffith"),
    PLAIN,
    PLAIN,
    PLAIN,
    city("Hobart", YELLOW, white(5), 2),
    PLAIN,
    PLAIN,
    UNPASSABLE,
    {
      type: SpaceType.UNPASSABLE,
      tile: {
        ...startFrom(TOP_LEFT).straightAcross(),
      },
    },
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    town("Highland"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Chesterton"),
    UNPASSABLE,
    {
      type: SpaceType.UNPASSABLE,
      tile: {
        ...startFrom(TOP_LEFT).curveLeft(),
        claimableCost: [10],
      },
    },
  ],
  [
    UNPASSABLE,
    city("Munster", YELLOW, black(3), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Lake Station"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    {
      type: SpaceType.UNPASSABLE,
      tile: {
        ...startFrom(TOP_LEFT).straightAcross(),
        claimableCost: [10],
      },
    },
    {
      type: SpaceType.UNPASSABLE,
      tile: {
        ...startFrom(BOTTOM_LEFT).straightAcross(),
      },
    },
  ],
  [
    PLAIN,
    PLAIN,
    town("Hammond"),
    PLAIN,
    PLAIN,
    city("Gary", RED, black(4), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    UNPASSABLE,
    UNPASSABLE,
    city("Michigan City", BLUE, black(6), 2),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Portage", BLUE, black(5), 2),
    {
      type: SpaceType.UNPASSABLE,
      tile: {
        ...startFrom(TOP).straightAcross(),
      },
    },
    {
      type: SpaceType.UNPASSABLE,
      tile: {
        ...startFrom(TOP).straightAcross(),
        claimableCost: [12],
      },
    },
    {
      type: SpaceType.UNPASSABLE,
      tile: {
        ...startFrom(TOP).curveRight(),
      },
    },
  ],
  [CHICAGO_SIDE, CHICAGO_CENTER, PLAIN, town("East Chicago")],
  [UNPASSABLE, UNPASSABLE, CHICAGO_SIDE, PLAIN],
]);
