import { CityData, SpaceData } from "../../engine/state/space";
import {
  black,
  city,
  grid,
  PLAIN,
  town,
  UNPASSABLE,
  WATER,
  white,
} from "../factory";
import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { SpaceType } from "../../engine/state/location_type";
import { CityGroup } from "../../engine/state/city_group";

export const CHICAGO_SAME_CITY = 1;

const CHICAGO_SIDE: CityData = {
  type: SpaceType.CITY,
  sameCity: CHICAGO_SAME_CITY,
  color: [RED],
  name: "",
  goods: [],
  onRoll: [],
  group: CityGroup.BLACK,
  startingNumCubes: 0,
};
const CHICAGO_CENTER: CityData = {
  type: SpaceType.CITY,
  sameCity: CHICAGO_SAME_CITY,
  color: [RED],
  name: "To Chicago",
  goods: [],
  onRoll: [black(1), black(2)],
  startingNumCubes: 2,
};

export const map = grid<SpaceData>([
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    city("Cedar Lake", YELLOW, [white(2)], 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Winfield"),
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Crown Point", PURPLE, white(4), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    town("Saint John"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Wheeler"),
    PLAIN,
    city("Valparaiso", YELLOW, white(6), 3),
    PLAIN,
  ],
  [
    UNPASSABLE,
    town("Dyer"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Merrillville", RED, white(3), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    city("Schererville", PURPLE, white(1), 3),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Griffith"),
    PLAIN,
    PLAIN,
    PLAIN,
    city("Hobart", YELLOW, white(5), 2),
    PLAIN,
    PLAIN,
    town("Westville"),
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    town("Highland"),
    PLAIN,
    PLAIN,
    PLAIN,
    town("Lake Station"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    city("Munster", YELLOW, black(3), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("La Porte"),
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Gary", RED, black(4), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Chesterton"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    town("Hammond"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Portage", BLUE, black(5), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    CHICAGO_SIDE,
    CHICAGO_CENTER,
    PLAIN,
    PLAIN,
    town("East Chicago"),
    PLAIN,
    PLAIN,
    PLAIN,
    WATER,
    WATER,
    WATER,
    PLAIN,
    PLAIN,
    city("Michigan City", BLUE, [black(6)], 2),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    CHICAGO_SIDE,
    PLAIN,
    PLAIN,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    PLAIN,
  ],
]);
