import { SpaceData } from "../../engine/state/space";
import {
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
} from "../factory";
import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";

export const map = grid<SpaceData>([
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    city("Totland", PURPLE, [], 3),
  ],
  [UNPASSABLE, UNPASSABLE, UNPASSABLE, PLAIN, PLAIN, PLAIN, PLAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city("Yarmouth", RED, [], 2),
    PLAIN,
    PLAIN,
  ],
  [UNPASSABLE, UNPASSABLE, PLAIN, PLAIN, town("Afton")],
  [UNPASSABLE, UNPASSABLE, town("Hamstead"), PLAIN, PLAIN, MOUNTAIN],
  [
    UNPASSABLE,
    RIVER,
    PLAIN,
    town("Newbridge"),
    MOUNTAIN,
    city("Brightstone", BLUE, [], 2),
  ],
  [
    UNPASSABLE,
    city("Thorness Bay", RED, [], 2),
    RIVER,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Atherfield"),
    PLAIN,
  ],
  [
    city("Cowes", RED, [], 2),
    RIVER,
    RIVER,
    city("Newport", YELLOW, [], 4),
    MOUNTAIN,
    town("Rookley"),
    MOUNTAIN,
    MOUNTAIN,
    city("Niton", RED, [], 2),
  ],
  [
    PLAIN,
    town("Whippingham"),
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    RIVER,
    RIVER,
    MOUNTAIN,
    town("Arreton"),
    MOUNTAIN,
    town("Whiteley Bank"),
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    town("Fishbourne"),
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    city("Ventnor", RED, [], 3),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    town("Havenstreet"),
    MOUNTAIN,
    MOUNTAIN,
    city("Sanklin", RED, [], 2),
    PLAIN,
  ],
  [UNPASSABLE, city("Ryde", BLUE, [], 3), PLAIN, PLAIN, MOUNTAIN, PLAIN],
  [UNPASSABLE, UNPASSABLE, PLAIN, PLAIN, PLAIN, town("Sandown")],
  [UNPASSABLE, town("Seaview"), RIVER, PLAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city("Bembridge", PURPLE, [], 3),
  ],
]);
