import { SpaceData } from "../../engine/state/space";
import { city, grid, HILL, PLAIN, RIVER, town, UNPASSABLE } from "../factory";
import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";

export const map = grid<SpaceData>([
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    city("Totland", PURPLE, [], 3),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city("Yarmouth", RED, [], 2),
    PLAIN,
    PLAIN,
  ],
  [UNPASSABLE, UNPASSABLE, UNPASSABLE, PLAIN, PLAIN, PLAIN],
  [UNPASSABLE, UNPASSABLE, PLAIN, PLAIN, town("Afton")],
  [UNPASSABLE, UNPASSABLE, city("Hamstead", RED, [], 2), PLAIN, PLAIN, HILL],
  [
    UNPASSABLE,
    RIVER,
    PLAIN,
    town("Newbridge"),
    HILL,
    city("Brightstone", BLUE, [], 2),
  ],
  [UNPASSABLE, town("Thorness Bay"), RIVER, PLAIN, HILL, HILL, HILL],
  [PLAIN, PLAIN, PLAIN, HILL, HILL, HILL, town("Atherfield"), PLAIN],
  [
    city("Cowes", RED, [], 2),
    RIVER,
    RIVER,
    city("Newport", YELLOW, [], 5),
    HILL,
    town("Rookley"),
    HILL,
    HILL,
    city("Niton", RED, [], 2),
  ],
  [PLAIN, town("Whippingham"), PLAIN, HILL, HILL, HILL, HILL, HILL],
  [
    UNPASSABLE,
    RIVER,
    RIVER,
    HILL,
    town("Arreton"),
    HILL,
    town("Whiteley Bank"),
    HILL,
    HILL,
  ],
  [
    UNPASSABLE,
    town("Fishbourne"),
    PLAIN,
    HILL,
    HILL,
    HILL,
    HILL,
    city("Ventnor", RED, [], 4),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    town("Havenstreet"),
    HILL,
    HILL,
    city("Sanklin", RED, [], 2),
    PLAIN,
  ],
  [UNPASSABLE, city("Ryde", BLUE, [], 4), PLAIN, PLAIN, HILL, PLAIN],
  [UNPASSABLE, UNPASSABLE, PLAIN, PLAIN, PLAIN, town("Sandown")],
  [UNPASSABLE, town("Seaview"), RIVER, PLAIN],
  [UNPASSABLE, UNPASSABLE, UNPASSABLE, city("Bembridge", PURPLE, [], 3)],
]);
