import { SpaceData } from "../../engine/state/space";
import {
  black,
  city,
  grid,
  HILL,
  RIVER,
  town,
  UNPASSABLE,
  white,
} from "../factory";
import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";

export const map = grid<SpaceData>([
  [
    UNPASSABLE,
    city("Swanton", BLUE, white(1), 3),
    HILL,
    RIVER,
    city("Burlington", RED, white(4), 3),
    HILL,
    HILL,
    city("Bristol", YELLOW, black(1), 3),
    RIVER,
    town("Brandon"),
    HILL,
    HILL,
    RIVER,
    RIVER,
    HILL,
    HILL,
    city("Bennington", PURPLE, black(5), 4),
  ],
  [
    RIVER,
    HILL,
    RIVER,
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
    RIVER,
    city("Rutland", BLUE, black(3), 3),
    HILL,
    HILL,
    town("Manchester Center"),
    HILL,
    HILL,
  ],
  [
    UNPASSABLE,
    RIVER,
    HILL,
    town("Cambridge"),
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
    RIVER,
    RIVER,
    HILL,
    HILL,
    HILL,
    town("Readsboro"),
  ],
  [
    RIVER,
    HILL,
    RIVER,
    HILL,
    HILL,
    HILL,
    town("Northfield"),
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
  ],
  [
    UNPASSABLE,
    HILL,
    HILL,
    town("Morrisville"),
    HILL,
    city("Montpelior", BLUE, white(5), 3),
    HILL,
    HILL,
    HILL,
    HILL,
    town("Woodstock"),
    HILL,
    town("Springfield"),
    HILL,
    HILL,
    HILL,
    city("Brattleboro", RED, black(6), 3),
  ],
  [
    HILL,
    HILL,
    HILL,
    RIVER,
    HILL,
    HILL,
    HILL,
    town("Randolf"),
    HILL,
    HILL,
    HILL,
    HILL,
    HILL,
    city("Bellows Falls", YELLOW, black(4), 3),
    HILL,
    HILL,
  ],
  [UNPASSABLE, HILL, HILL, town("Cabol"), HILL, HILL, HILL, HILL, HILL, HILL],
  [
    city("Newport", RED, white(2), 4),
    HILL,
    HILL,
    RIVER,
    town("St. Johnsbury"),
    HILL,
    HILL,
    city("Branford", PURPLE, black(2), 3),
  ],
  [UNPASSABLE, HILL, HILL, HILL, HILL, HILL],
  [HILL, HILL, HILL, city("Lyndonville", YELLOW, white(6), 3), HILL],
  [UNPASSABLE, city("Island Pond", PURPLE, white(3), 4), HILL, HILL, HILL],
  [HILL, HILL, HILL, HILL],
]);
