import { SpaceData } from "../../engine/state/space";
import {
  black,
  city,
  grid,
  MOUNTAIN,
  RIVER,
  town,
  UNPASSABLE,
  white,
} from "../factory";
import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";

export const map = grid<SpaceData>([
  [
    UNPASSABLE,
    city("Swanton", BLUE, white(1), 3),
    MOUNTAIN,
    RIVER,
    city("Burlington", RED, white(4), 3),
    MOUNTAIN,
    MOUNTAIN,
    city("Bristol", YELLOW, black(1), 3),
    RIVER,
    town("Brandon"),
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    city("Bennington", PURPLE, black(5), 4),
  ],
  [
    RIVER,
    MOUNTAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    city("Rutland", BLUE, black(3), 3),
    MOUNTAIN,
    MOUNTAIN,
    town("Manchester Center"),
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    RIVER,
    MOUNTAIN,
    town("Cambridge"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Readsboro"),
  ],
  [
    RIVER,
    MOUNTAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Northfield"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    town("Morrisville"),
    MOUNTAIN,
    city("Montpelior", BLUE, white(5), 3),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Woodstock"),
    MOUNTAIN,
    town("Springfield"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    city("Brattleboro", RED, black(6), 3),
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Randolf"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    city("Bellows Falls", YELLOW, black(4), 3),
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    town("Cabol"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
  ],
  [
    city("Newport", RED, white(2), 4),
    MOUNTAIN,
    MOUNTAIN,
    RIVER,
    town("St. Johnsbury"),
    MOUNTAIN,
    MOUNTAIN,
    city("Branford", PURPLE, black(2), 3),
  ],
  [UNPASSABLE, MOUNTAIN, MOUNTAIN, MOUNTAIN, MOUNTAIN, MOUNTAIN],
  [
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    city("Lyndonville", YELLOW, white(6), 3),
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    city("Island Pond", PURPLE, white(3), 4),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
  ],
  [MOUNTAIN, MOUNTAIN, MOUNTAIN, MOUNTAIN],
]);
