import { SpaceData } from "../../engine/state/space";
import {
  black,
  city,
  DARK_MOUNTAIN,
  grid,
  MOUNTAIN,
  PLAIN,
  town,
  UNPASSABLE,
  WATER,
} from "../factory";
import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";

export const map = grid<SpaceData>([
  [
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    city("Green River", BLUE, black(5), 2),
    MOUNTAIN,
    MOUNTAIN,
    DARK_MOUNTAIN,
    MOUNTAIN,
    city("Cheyenne", RED, black(6), 2),
    PLAIN,
  ],
  [
    MOUNTAIN,
    town("Kemmerer"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Rawlins"),
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    MOUNTAIN,
    MOUNTAIN,
    town("Lander"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Douglas"),
    PLAIN,
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    DARK_MOUNTAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    city("Casper", YELLOW, black(4), 2),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    city("Jackson", RED, black(2), 2),
    DARK_MOUNTAIN,
    MOUNTAIN,
    city("Thermopolis", PURPLE, black(3), 2),
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Newcastle"),
  ],
  [
    MOUNTAIN,
    MOUNTAIN,
    DARK_MOUNTAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Buffalo"),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    WATER,
    DARK_MOUNTAIN,
    town("Cody"),
    DARK_MOUNTAIN,
    town("Sheridan"),
    PLAIN,
    PLAIN,
    city("Gillette", YELLOW, black(1), 2),
    PLAIN,
  ],
]);
