import z from "zod";
import { SpaceData } from "../../engine/state/space";
import {
  black,
  city,
  grid,
  PLAIN,
  RIVER,
  town,
  UNPASSABLE,
  WATER,
  white,
} from "../factory";
import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";

export const POLDER_STYLE = "polder";

export const HollandMapData = z.object({
  polder: z.boolean().optional(),
  windmill: z.boolean().optional(),
});
export type HollandMapData = z.infer<typeof HollandMapData>;

const POLDER = {
  ...RIVER,
  style: POLDER_STYLE,
  mapSpecific: {
    polder: true,
  },
};

const WINDMILL = {
  ...RIVER,
  style: POLDER_STYLE,
  mapSpecific: {
    polder: true,
    windmill: true,
  },
};

export const map = grid<SpaceData>([
  [
    UNPASSABLE,
    city("Schledam", PURPLE, black(6), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    city("Rotterdam", BLUE, black(5), 2),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    town("Vlaardingen"),
    PLAIN,
    PLAIN,
    PLAIN,
    town("Dordrecht"),
  ],
  [UNPASSABLE, WINDMILL, POLDER, POLDER, PLAIN, PLAIN, PLAIN, PLAIN, PLAIN],
  [POLDER, PLAIN, PLAIN, POLDER, PLAIN, town("Lansingerland"), PLAIN, PLAIN],
  [
    UNPASSABLE,
    PLAIN,
    city("Delft", YELLOW, [], 2),
    POLDER,
    POLDER,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Gouda", BLUE, black(4), 2),
  ],
  [POLDER, POLDER, WINDMILL, PLAIN, POLDER, POLDER, PLAIN, PLAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    city("Den Haag", RED, [white(5), white(5)], 2),
    POLDER,
    town("Zoetermeer"),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    POLDER,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Teylingen"),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    town("Katwijk"),
    PLAIN,
    city("Leiden", RED, [white(3), white(4)], 2),
    PLAIN,
    PLAIN,
    PLAIN,
    town("Nieuwkoop"),
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    POLDER,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Aalsmeer"),
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    town("Zandvoort"),
    PLAIN,
    city("Haarlem", RED, [white(1), white(2)], 2),
    POLDER,
    POLDER,
    PLAIN,
    city("Amsterdam", BLUE, black(3), 2),
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    WINDMILL,
    PLAIN,
    PLAIN,
    POLDER,
    city("Zaandam", YELLOW, [], 2),
    POLDER,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    POLDER,
    town("Velsen"),
    POLDER,
    POLDER,
    POLDER,
    POLDER,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    POLDER,
    PLAIN,
    PLAIN,
    POLDER,
    POLDER,
    town("Purmerend"),
    PLAIN,
    town("Edam"),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    POLDER,
    town("Beverwijk"),
    POLDER,
    POLDER,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    POLDER,
    POLDER,
    POLDER,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    POLDER,
    town("Castricum"),
    WATER,
    city("Alkmaar", BLUE, black(1), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    city("Hoorn", PURPLE, black(2), 2),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    POLDER,
    PLAIN,
    WINDMILL,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    POLDER,
    POLDER,
    POLDER,
    POLDER,
    POLDER,
    WINDMILL,
    POLDER,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    POLDER,
    town("Den Helder"),
    PLAIN,
    PLAIN,
    city("Medemblik", BLUE, [], 2),
  ],
]);
