import { LandData, SpaceData } from "../../engine/state/space";
import {
  black,
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  town,
  UNPASSABLE,
  white,
} from "../factory";
import { BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { SpaceType } from "../../engine/state/location_type";

const LAKE: LandData = {
  type: SpaceType.LAKE,
};

const PEARL_CITY_WAIPAHU_SAME_CITY = 1;
const HONOLULU_SAME_CITY = 2;

export const map = grid<SpaceData>([
  [UNPASSABLE, UNPASSABLE, UNPASSABLE, PLAIN],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    MOUNTAIN,
    PLAIN,
    city("Makaha", YELLOW, black(4), 2),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    town("Waialua"),
    MOUNTAIN,
    MOUNTAIN,
    town("Waianae"),
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    city("Nanakuli", RED, black(5), 2),
    MOUNTAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    city("Haleiwa", BLUE, black(2), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Makakailo"),
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    city("Wahiawa", YELLOW, black(3), 2),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    town("Waimea"),
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Mililani"),
    PLAIN,
    LAKE,
    PLAIN,
    city("Ewa", RED, black(6), 2),
  ],
  [
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Whitmore Village"),
    MOUNTAIN,
    PLAIN,
    PLAIN,
    {
      ...city("Waipahu", YELLOW, white(2), 2),
      sameCity: PEARL_CITY_WAIPAHU_SAME_CITY,
    },
    LAKE,
    LAKE,
    LAKE,
  ],
  [
    town("Kahuku"),
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    {
      ...city("Pearl City", YELLOW, [], 0),
      sameCity: PEARL_CITY_WAIPAHU_SAME_CITY,
    },
    LAKE,
    town("Pearl Harbor"),
    LAKE,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    city("Laie", BLUE, black(1), 2),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    LAKE,
    LAKE,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    town("Waikane"),
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    {
      ...city("Honolulu", PURPLE, [white(5), white(6)], 2),
      sameCity: HONOLULU_SAME_CITY,
    },
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    town("Kaawa"),
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
    {
      ...city("", PURPLE, [], 0),
      sameCity: HONOLULU_SAME_CITY,
    },
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    city("Kaneohe", PURPLE, white(1), 2),
    PLAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
    town("Kailua"),
    PLAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    MOUNTAIN,
    town("Hawaii Kai"),
  ],
  [
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    UNPASSABLE,
    PLAIN,
  ],
]);
