import { Good } from '../../engine/state/good';
import { BOTTOM, BOTTOM_LEFT, BOTTOM_RIGHT, TOP, TOP_LEFT, TOP_RIGHT } from '../../engine/state/tile';
import { duplicate } from '../../utils/functions';
import { black, city, MOUNTAIN, PLAIN, startsLowerGrid, town, UNPASSABLE, white } from '../factory';
import { river } from '../texture_factory';

export const map = startsLowerGrid([
  [
    PLAIN,
    UNPASSABLE,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    city('Pittsburgh', Good.RED, black(5), 3),
    ...duplicate(4, MOUNTAIN),
  ],
  [
    PLAIN,
    city('Toronto', Good.YELLOW, black(6)),
    river(TOP_LEFT, BOTTOM),
    UNPASSABLE,
    PLAIN,
    PLAIN,
    river(TOP_LEFT, BOTTOM),
    river(TOP, BOTTOM_RIGHT),
    city('Wheeling', Good.YELLOW, black(4), 3),
    MOUNTAIN,
  ],
  [
    ...duplicate(3, PLAIN),
    UNPASSABLE,
    town('Cleveland'),
    PLAIN,
    PLAIN,
    river(TOP_LEFT, BOTTOM_RIGHT),
    PLAIN,
    MOUNTAIN,
  ],
  [
    UNPASSABLE,
    ...duplicate(3, PLAIN),
    UNPASSABLE,
    ...duplicate(3, PLAIN),
    river(TOP_LEFT, BOTTOM_RIGHT),
    town('Lexington'),
    MOUNTAIN,
  ],
  [
    ...duplicate(3, UNPASSABLE),
    city('Detroit', Good.RED, black(3)),
    UNPASSABLE,
    ...duplicate(3, PLAIN),
    river(TOP_LEFT, BOTTOM_RIGHT),
    PLAIN,
  ],
  [
    ...duplicate(3, UNPASSABLE),
    PLAIN,
    PLAIN,
    town('Toledo'),
    PLAIN,
    PLAIN,
    city('Cincinatti', Good.BLUE, black(2)),
    river(TOP_LEFT, BOTTOM_RIGHT),
    PLAIN,
  ],
  [
    UNPASSABLE,
    ...duplicate(5, PLAIN),
    town('Fort Wayne'),
    PLAIN,
    PLAIN,
    river(TOP_LEFT, BOTTOM_RIGHT),
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    town('Grand Rapids'),
    ...duplicate(4, PLAIN),
    town('Indianapolis'),
    PLAIN,
    river(TOP_LEFT, BOTTOM_RIGHT),
  ],
  [
    ...duplicate(5, UNPASSABLE),
    town('Michigan City'),
    PLAIN,
    PLAIN,
    PLAIN,
    city('Evansville', Good.BLUE, black(1)),
  ],
  [
    PLAIN,
    ...duplicate(5, UNPASSABLE),
    PLAIN,
    PLAIN,
    town('Terre Haute'),
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    town('Green Bay'),
    PLAIN,
    town('Milwaukee'),
    PLAIN,
    city('Chicago', Good.RED, white(1)),
    ...duplicate(4, PLAIN),
  ],
  [
    ...duplicate(8, PLAIN),
    town('Springfield'),
    river(TOP_RIGHT, BOTTOM),
    river(TOP, BOTTOM),
  ],
  [
    ...duplicate(6, PLAIN),
    town('Rock Island'),
    PLAIN,
    river(TOP_RIGHT, BOTTOM_LEFT),
    city('St. Louis', Good.RED, white(2)),
  ],
  [
    UNPASSABLE,
    ...duplicate(2, PLAIN),
    town('La Crosse'),
    river(TOP_RIGHT, BOTTOM),
    river(TOP, BOTTOM),
    river(TOP, BOTTOM),
    river(TOP, BOTTOM),
    river(TOP, BOTTOM_LEFT),
    PLAIN,
    PLAIN,
  ],
  [
    UNPASSABLE,
    PLAIN,
    PLAIN,
    river(TOP_RIGHT, BOTTOM_LEFT),
    ...duplicate(6, PLAIN),
  ],
  [
    city('Deluth', Good.PURPLE, white(6)),
    ...duplicate(2, PLAIN),
    river(TOP_RIGHT, BOTTOM_LEFT),
    ...duplicate(3, PLAIN),
    city('Desmoines', Good.BLUE, white(4)),
    ...duplicate(3, PLAIN),
  ],
  [
    ...duplicate(2, PLAIN),
    city('Minneapolis', Good.BLUE, white(5)),
    ...duplicate(6, PLAIN),
    city('Kansas City', Good.PURPLE, white(3)),
  ],
]);
