import { SpaceData } from "../../engine/state/space";
import {
  black,
  city,
  grid,
  MOUNTAIN,
  PLAIN,
  town,
  WATER,
  white,
} from "../factory";
import { BLACK, BLUE, PURPLE, RED, YELLOW } from "../../engine/state/good";
import { duplicate } from "../../utils/functions";

export const map = grid<SpaceData>([
  [city("Tiquana", BLUE, white(1)), PLAIN, PLAIN, ...duplicate(8, WATER)],
  [PLAIN, PLAIN, town("San Borja"), PLAIN, ...duplicate(7, WATER)],
  [PLAIN, PLAIN, PLAIN, WATER, PLAIN, PLAIN, ...duplicate(5, WATER)],
  [
    town("Tuscon"),
    PLAIN,
    city("Guaymas", BLUE, white(2)),
    WATER,
    WATER,
    city("La Paz", PURPLE, black(1)),
    ...duplicate(5, WATER),
  ],
  [PLAIN, MOUNTAIN, MOUNTAIN, MOUNTAIN, PLAIN, ...duplicate(6, WATER)],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    town("Mazatlah"),
    ...duplicate(5, WATER),
  ],
  [
    town("El Paso"),
    PLAIN,
    PLAIN,
    town("Conchos"),
    PLAIN,
    MOUNTAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    WATER,
    WATER,
  ],
  [
    PLAIN,
    city("Rio Grande", YELLOW, white(3)),
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    city("Guadalajara", YELLOW, black(4)),
    PLAIN,
    WATER,
    WATER,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    town("Monterrey"),
    PLAIN,
    town("Leon"),
    MOUNTAIN,
    PLAIN,
    PLAIN,
    WATER,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
    MOUNTAIN,
    PLAIN,
    city("Acapulco", BLUE, black(5)),
    WATER,
  ],
  [
    PLAIN,
    PLAIN,
    city("San Antonio", BLUE, white(4)),
    PLAIN,
    town("Matamoros"),
    PLAIN,
    PLAIN,
    PLAIN,
    city("Mexico", [RED, BLACK]),
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    PLAIN,
    WATER,
    WATER,
    WATER,
    city("Tampico", BLUE, black(2)),
    PLAIN,
    MOUNTAIN,
    MOUNTAIN,
    PLAIN,
  ],
  [
    PLAIN,
    town("Houston"),
    PLAIN,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    PLAIN,
    PLAIN,
    city("Santa Cruz", YELLOW, black(6)),
  ],
  [PLAIN, PLAIN, WATER, WATER, WATER, WATER, WATER, WATER, PLAIN, PLAIN, WATER],
  [
    PLAIN,
    PLAIN,
    city("New Orleans", YELLOW, white(5)),
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    MOUNTAIN,
    PLAIN,
  ],
  [
    PLAIN,
    PLAIN,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    town("Merida"),
    PLAIN,
    PLAIN,
    town("Usumacinta"),
  ],
  [
    PLAIN,
    city("Mobile", YELLOW, white(6)),
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    PLAIN,
    PLAIN,
    PLAIN,
    PLAIN,
  ],
  [
    PLAIN,
    WATER,
    WATER,
    WATER,
    WATER,
    WATER,
    city("Cancun", PURPLE, black(3)),
    PLAIN,
    WATER,
    WATER,
    WATER,
  ],
]);
