name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    # container: node:20-bookworm-slim

    permissions:
      contents: read
      checks: write

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - run: sudo apt-get update
      - run: sudo apt-get install unzip

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Running tests
        run: npm test

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "temurin"

      # - uses: browser-actions/setup-chrome@v1
      #   with:
      #     install-chromedriver: true
      #     install-dependencies: true
      #     chrome-version: 139

      - run: npm run build
      - run: npm run migrate-testdb-direct
        env:
          POSTGRES_URL: "postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres"
          NODE_ENV: "test"

      - name: Run e2e tests
        run: ./src/scripts/deflake.sh "npm run e2e-test"
        env:
          # User, port, and db seem to be hardcoded
          POSTGRES_URL: "postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres"
          NODE_ENV: "test"
          PORT: 3001
